# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resetful', '0002_auto_20171215_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
